name: "Install Node Dependencies"
description: "Install dependencies using yarn"
runs:
  using: "composite"
  steps:
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: ".nvmrc"
        cache: "yarn"
    - name: Install dependencies
      run: yarn install
      shell: bash
